project_id = "tuxslfemwkdmnkldlmmy"

[functions.generate-product-news]
verify_jwt = false

[functions.translate-keyword]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.ai-analyze-visitor]
verify_jwt = false

[functions.translate-content]
verify_jwt = false